### PR TITLE
replace matrix with two vectors

### PR DESCRIPTION
**Pull request by mikeantonacci**
Replaced the matrix with two vectors, since we only ever care about the previous and current rows.
Also use std::cmp::min instead of creating an array every iteration

Uses less memory and seems to be faster as well.

### CODE REVIEW

**Comment by febeling** [comment]
I have this idea to be able to visualize the calculation, and this optimization would destroy that information.

**Comment by Pfeil** [comment]
You could use the current state as a reference implementation for testing the optimized function. This way the "educational" code would be still there, but using the algorithm would be more efficient. Just a suggestion.

**Comment by mikeantonacci** [comment]
Hey, this seems like a strange decision to provide intentionally suboptimal code.

The suggestion from @Pfeil seems like a good one, would be happy to do whatever work is needed.

**Comment by febeling** [comment]
Yes, I also had second thoughts. As the idea with the educational features is only a that, an idea, it might make sense to apply well-known optimization to the algorithm. So I will reopen the PR.

**Comment by febeling** [comment]
@mikeantonacci the change doesn't apply cleanly any longer. Care to have a look?

**Comment by febeling** [comment]
Implemented in #13.

**Pull request closed without merging**
